- name: Setup Control plane kubernetes
  hosts: master
  become: true

  handlers:
    - name: Common Config
      include_tasks: commons.yml

  tasks:
    - command: "true"
      notify: Common Config
